[package]
name = "vsm"
version = "0.1.0"
authors = ["b <b@unyu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.26"
nalgebra-glm = "0.5"
arrayref = "0"
